### ISSUE TITLE
Bug pri risanju figur(mogoče povezan z osnovnim skeletom)

### ISSUE THREAD

**Issue by Mihec123** [jan-golob/Reversi#10]

**Comment by andrejbauer** [comment]
A bi kdo opisal ta bug, ali pa vsaj povedal, kje se pojavi, ko poženem kodo, da ne bom sam ugotavljal?

**Comment by Mihec123** [comment]
Bug se pojavlja pri izrisevanju kroglic na platno(izrise kroglice v prvo vrstico in prvi stolpec)
