### ISSUE TITLE
funkcija veljavna poteza

### ISSUE THREAD

**Issue by Mihec123** [jan-golob/Reversi#2]
Funkcija ki preveri, če je postavitev figure igralca, na izbrano polje sploh dovoljena.

**Comment by andrejbauer** [comment]
Kaj je s to funkcijo? Jo je treba popraviti, ali napisati, ali kaj? Izražanje v polnih stavkih dejansko pomaga, še posebej, če za tabo bere tvoj profesor, ki ni bil zraven, ko sta si zamislila issue ;-)
