### ISSUE TITLE
funkcija popravi matriko

### ISSUE THREAD

**Issue by Mihec123** [jan-golob/Reversi#3]
Funkcija, ki bo potem ko bo postavljena figura. Obrnila vse žetone, ki bi se mogli s tako potezo obrniti.

**Comment by andrejbauer** [comment]
Kaj to pomeni? Predstavljam si, da bosta imela matriko, v kateri bo trenutna pozicija. Za potrebe metoda minimax in alfa-beta, bo treba znati vleči poteze in tudi vračati stanje na prešnje stanje. Ta issue bi lahko pomenil katerokoli od teh dveh zadev.
