### ISSUE TITLE
povezava grafike z osnovnim skeletom

### ISSUE THREAD

**Issue by Mihec123** [jan-golob/Reversi#5]
naredi spremenljivko i_deska, ki bo razred Deska(iz datoteke skelet.py) in jo bo izrisala

**Comment by andrejbauer** [comment]
Kaj pa vem, če je res, da bo "osnovni skelet" povezan z grafiko. Bolj verjetno je, da bo glavni program dejansko kar uporabniški vmesnik (nikjer ne bo nobenega drugega skeleta). Potem bo še drugi del programa, A.I., in uporabniški vmesnik ga bo uporabljal (da bo preverjal veljavnost potez, vlekel poteze in računal računalnikove poteze). Kako sta si zamislila strukturo programa, koliko bo razredov, kaj bo naredil glavni program?
